sudo: required
dist: xenial

language: python
python: "3.5"

virtualenv:
  system_site_packages: true

env:
  global:
    - TEST_RUN_FOLDER="/tmp" # folder where the tests are run from

matrix:
  # Do not wait for the allowed_failures entry to finish before
  # setting the status
  fast_finish: true
  allow_failures:
    # allow_failures seems to be keyed on the python version.
    - python: 3.5
  include:
    # without matplotlib
    - env: DISTRIB="conda" PYTHON_VERSION="3.5"
           NUMPY_VERSION="1.11" SCIPY_VERSION="0.19" PANDAS_VERSION="*"
           SCIKIT_LEARN_VERSION="0.19" COVERAGE="true" JOBLIB_VERSION="*"
           LXML_VERSION="*"
    - env: DISTRIB="conda" PYTHON_VERSION="3.5"
           NUMPY_VERSION="*" SCIPY_VERSION="*" PANDAS_VERSION="*"
           SCIKIT_LEARN_VERSION="*" MATPLOTLIB_VERSION="*" COVERAGE="true"
           JOBLIB_VERSION="0.11"
           LXML_VERSION="*"
    - env: DISTRIB="conda" PYTHON_VERSION="3.6"
           NUMPY_VERSION="*" SCIPY_VERSION="*" PANDAS_VERSION="*"
           SCIKIT_LEARN_VERSION="*" MATPLOTLIB_VERSION="*" COVERAGE="true"
           JOBLIB_VERSION="*"
           LXML_VERSION="*"
    - env: DISTRIB="conda" PYTHON_VERSION="3.7"
           NUMPY_VERSION="*" SCIPY_VERSION="*" PANDAS_VERSION="*"
           SCIKIT_LEARN_VERSION="*" MATPLOTLIB_VERSION="*" COVERAGE="true"
           JOBLIB_VERSION="0.12" LXML_VERSION="*"

  # FLAKE8 linting on diff wrt common ancestor with upstream/master
    # Note: the python value is only there to trigger allow_failures
    - python: 3.5
      env: DISTRIB="conda" PYTHON_VERSION="3.5" FLAKE8_VERSION="*" SKIP_TESTS="true"

install: source continuous_integration/install.sh

before_script: make  clean

script: source continuous_integration/test_script.sh

after_success: source continuous_integration/after_success.sh
