sudo: required
dist: xenial

language: python

env:
  global:
    - TEST_RUN_FOLDER="/tmp"

matrix:
  # Do not wait for the allowed_failures entry to finish before
  # setting the status
  fast_finish: true
  allow_failures:
    # allow_failures keyed to python 3.5 & skipping tests.
    - python: "3.5"
      env: DISTRIB="travisci" PYTHON_VERSION="3.5" FLAKE8_VERSION="*" SKIP_TESTS="true"
    - python: "3.7"
      env: DISTRIB="travisci" PIP_FLAGS="--pre" COVERAGE="true"
           NUMPY_VERSION="*" SCIPY_VERSION="*" PANDAS_VERSION="*"
           SCIKIT_LEARN_VERSION="*" JOBLIB_VERSION="*" LXML_VERSION="*"
  include:
    - name: "Python 3.5 minimum package versions without Matplotlib"
      python: "3.5"
      env: DISTRIB="travisci" PYTHON_VERSION="3.5" NIBABEL_VERSION="2.0.2"
           NUMPY_VERSION="1.11" SCIPY_VERSION="0.19" PANDAS_VERSION="0.23.0"
           SCIKIT_LEARN_VERSION="0.19" COVERAGE="true" JOBLIB_VERSION="0.11"
           LXML_VERSION="*"
    - name: "Python 3.5 latest package versions"
      python: "3.5"
      env: DISTRIB="travisci" PYTHON_VERSION="3.5"
           NUMPY_VERSION="*" SCIPY_VERSION="*" PANDAS_VERSION="*"
           SCIKIT_LEARN_VERSION="*" MATPLOTLIB_VERSION="*" COVERAGE="true"
           JOBLIB_VERSION="0.11"
           LXML_VERSION="*"
    - name: "Python 3.6 latest package versions"
      python: "3.6"
      env: DISTRIB="travisci" PYTHON_VERSION="3.6"
           NUMPY_VERSION="*" SCIPY_VERSION="*" PANDAS_VERSION="*"
           SCIKIT_LEARN_VERSION="*" MATPLOTLIB_VERSION="*" COVERAGE="true"
           JOBLIB_VERSION="0.12" LXML_VERSION="*"
      # joblib.Memory switches from keyword cachedir to location in version 0.12
      # Making sure we get the deprecation warning.

    - name: "Python 3.7 latest package versions"
      python: "3.7"
      env: DISTRIB="travisci" PYTHON_VERSION="3.7"
           NUMPY_VERSION="*" SCIPY_VERSION="*" PANDAS_VERSION="*"
           SCIKIT_LEARN_VERSION="*" MATPLOTLIB_VERSION="*" COVERAGE="true"
           JOBLIB_VERSION="*" LXML_VERSION="*"

    - name: "Python 3.7 pre-release checks"
      python: "3.7"
      env: DISTRIB="travisci" PIP_FLAGS="--pre" COVERAGE="true"
           NUMPY_VERSION="*" SCIPY_VERSION="*" PANDAS_VERSION="*"
           SCIKIT_LEARN_VERSION="*" JOBLIB_VERSION="*" LXML_VERSION="*"

  # FLAKE8 linting on diff wrt common ancestor with upstream/master
    # Note: the python value is only there to trigger allow_failures
    - name: Python 3.5 Flake8 no tests
      python: "3.5"
      env: DISTRIB="travisci" PYTHON_VERSION="3.5" FLAKE8_VERSION="*" SKIP_TESTS="true"

install: source continuous_integration/install.sh

before_script: make  clean

script: source continuous_integration/test_script.sh

after_success: source continuous_integration/after_success.sh
