language: python

virtualenv:
  system_site_packages: true

env:
  matrix:
    - DISTRIB="neurodebian-no-matplotlib" PYTHON_VERSION="2.7"
    - DISTRIB="conda" PYTHON_VERSION="2.6"
      NUMPY_VERSION="1.9.1" SCIPY_VERSION="0.15.1"
      MATPLOTLIB_VERSION="1.4.2" SKLEARN_VERSION="0.15.2"
      NIBABEL_VERSION="2.0.0"
    - DISTRIB="conda" PYTHON_VERSION="2.6"
      NUMPY_VERSION="1.7.0" SCIPY_VERSION="0.11.0"
      MATPLOTLIB_VERSION="1.2.0" SKLEARN_VERSION="0.12.1"
      NIBABEL_VERSION="1.3.0"

install: 
    - source continuous_integration/install.sh

before_script:
    - make clean

script:
    - python continuous_integration/show-python-packages-versions.py
    - make test-code
