---
# Workflow to check the time taken to run tests and build the documentation.
#
# Pings Github API to collect information about:
#
# - how long each run of the test suite lasted,
# - how long the build of the doc lasted.
#
# Plots the results and saves it as an artifact to download and manually inspect
# to see if there is a trend in tests or doc build taking longer.
#
# .. seealso::
#
#       `maint_tools/check_gha_workflow.py <https://github.com/nilearn/nilearn/blob/main/maint_tools/check_gha_workflow.py>`_
#
###
name: Benchmark test suite

on:
    schedule:
        # Uses the cron schedule for github actions
        # https://docs.github.com/en/actions/reference/workflows-and-actions/events-that-trigger-workflows#schedule
        # Run every Monday at midnight UTC
        #     ┌───────────── minute (0 - 59)
        #     │ ┌───────────── hour (0 - 23)
        #     │ │ ┌───────────── day of the month (1 - 31)
        #     │ │ │ ┌───────────── month (1 - 12 or JAN-DEC)
        #     │ │ │ │ ┌───────────── day of the week (0 - 6 or SUN-SAT)
        #     │ │ │ │ │
        #     │ │ │ │ │
        #     │ │ │ │ │
        #     * * * * *
    -   cron: 0 0 * * 1

    # This enables manual triggering from GitHub UI
    # https://docs.github.com/en/actions/reference/workflows-and-actions/events-that-trigger-workflows#workflow_dispatch
    workflow_dispatch:

jobs:
    check_gha_workflow:
        if: github.repository == 'nilearn/nilearn'
        runs-on: ubuntu-latest
        permissions: {}
        steps:
        -   name: Checkout nilearn
            uses: actions/checkout@v6
        -   name: Setup python
            uses: actions/setup-python@v6
            with:
                python-version: 3.14
        -   name: Install dependencies
            run: python -m pip install --requirement maint_tools/requirements.txt
        -   name: Collect and plot test suite run time
            run: python maint_tools/check_gha_workflow.py ${{ secrets.GITHUB_TOKEN }}
        -   name: Upload output
            uses: actions/upload-artifact@v6
            with:
                name: test_runs_timing_outputs
                path: maint_tools/*_runs_timing.*
