---
name: check deprecations

# Runs once a month.
# Checks for deprecations of core dependencies of nilearn
# Turns deprecation warnings into errors so we can handle
# them before an actual failure happens.

on:

# Uses the cron schedule for github actions
#
# https://docs.github.com/en/free-pro-team@latest/actions/reference/events-that-trigger-workflows#scheduled-events
#
#            ┌───────────── minute (0 - 59)
#            │ ┌───────────── hour (0 - 23)
#            │ │ ┌───────────── day of the month (1 - 31)
#            │ │ │ ┌───────────── month (1 - 12 or JAN-DEC)
#            │ │ │ │ ┌───────────── day of the week (0 - 6 or SUN-SAT)
#            │ │ │ │ │
#            │ │ │ │ │
#            │ │ │ │ │
#            * * * * *
    schedule:
    -   cron: 0 0 25 * * # on the 25th of every monday

  # Allows you to run this workflow manually from the Actions tab
    workflow_dispatch:

jobs:
    deprecations:
        if: github.repository == 'nilearn/nilearn'
        runs-on: ubuntu-latest
        env:
            # TODO: Add another env variable that will be used in conftest.py
            PIP_FLAGS: --pre
        defaults:
            run:
                shell: bash
        steps:
        -   uses: actions/checkout@v4

        -   name: Setup python
            uses: actions/setup-python@v4
            with:
                python-version: 3.11

        -   name: Display Python version
            run: python -c "import sys; print(sys.version)"

        -   name: Install dependencies
            run: ./build_tools/github/dependencies.sh

        -   name: Install nilearn
            run: ./build_tools/github/install.sh

        -   name: Run tests
            run: python -m pytest --pyargs nilearn
