---
# Workflow to test against the latest nightly releases of development
# versions of Numpy 2.0 ahead of its upcoming release
name: Numpy2 compatibility

on:
    schedule:
    # Run every day at 8am UTC
    -   cron: 0 8 * * *
    workflow_dispatch:

jobs:
    test_numpy2:
        if: github.repository == 'nilearn/nilearn'
        runs-on: ubuntu-latest
        steps:
        -   name: Checkout nilearn
            uses: actions/checkout@v4
        -   name: Setup python
            uses: actions/setup-python@v4
            with:
                python-version: 3.12
        -   name: Install tox
            run: python -m pip install tox
        -   name: Run test suite
            run: tox run -e test_numpy2 -- nilearn
